const express = require('express');
const router = express.Router();

const userRoutes = require('./userRoutes');
const teacherRoutes = require('./teacherRoutes');
const subjectRoutes = require('./subjectRoutes');
const classRoutes = require('./classRoutes');
const feeRoutes = require('./feeRoutes');
const reportRoutes = require('./reportRoutes');
const examRoutes = require('./examRoutes');
const studentRoutes = require('./studentRoutes');
const attendanceRoutes = require('./attendanceRoutes');
const notificationRoutes = require('./notificationRoutes');
const eventRoutes = require('./eventRoutes');
const parentRoutes = require('./parentRoutes');
const libraryRoutes = require('./libraryRoutes');
const complaintRoutes = require('./complaintRoutes');
const holidayRoutes = require('./holidayRoutes');
const resultRoutes = require('./resultRoutes');
const timetableRoutes = require('./timetableRoutes');
const transportRoutes = require('./transportRoutes');
const gradeRoutes = require('./gradeRoutes');
const authRoutes = require('./authRoutes');
const parentMessageRoutes = require('./parentMessageRoutes');
const teacherTaskRoutes = require('./teacherTaskRoutes');
const mlRoutes = require('./mlRoutes');

router.use('/users', userRoutes);
router.use('/teachers', teacherRoutes);
router.use('/subjects', subjectRoutes);
router.use('/classes', classRoutes);
router.use('/fees', feeRoutes);
router.use('/reports', reportRoutes);
router.use('/exams', examRoutes);
router.use('/students', studentRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/notifications', notificationRoutes);
router.use('/events', eventRoutes);
router.use('/parents', parentRoutes);
router.use('/library', libraryRoutes);
router.use('/complaints', complaintRoutes);
router.use('/holidays', holidayRoutes);
router.use('/results', resultRoutes);
router.use('/timetables', timetableRoutes);
router.use('/transport', transportRoutes);
router.use('/grades', gradeRoutes);
router.use('/auth', authRoutes);
router.use('/parent-messages', parentMessageRoutes);
router.use('/teacher-tasks', teacherTaskRoutes);
router.use('/ml', mlRoutes);

module.exports = router; 